### ISSUE TITLE
R1 - TODO tracker

### ISSUE THREAD

**Issue by Smidqe** [Smidqe/gmanager#1]
- [ ] Implement a subsystem that handles loading the settings (and all other ini files?)
- [x] Implement the caching system, so there is no need for downloading images from internet again
- [x] Figure out why the GUI goes white when handling too many imageviews/tiles
- ~~Was fixed, it must be somehow related to the tilepane when it resizes, or something related to that~~
- ~~This could be because of how we load images (somewhat worked it out right now)~~
- The reason was that when reloading the image we accessed the imageview from a different thread instead of the FX-thread.
- [x] Figure out why gifs won't work in thumbnails 
- Same as above
- [x] Offload all work from FX-thread
